version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g aws-cdk
      - cd aws
      - npm install
      - cd ../
  build:
    commands:
      # create folder, cuz cdk expect dist folder even if it is not used by the current command
      - mkdir -p client/dist
      - cd aws
      - npm run build
      - cdk deploy $CD_STACK_NAME --app="npx ts-node cd-index.ts" --require-approval=never
