version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g aws-cdk
      - cd aws
      - npm install
      - cd src/pipedrive
      - npm install
      - cd ../../../
      - cd client
      - npm install
      - cd ../
  build:
    commands:
      - cd client
      - npm run generate
      - cd ../aws
      - npm run build
      - cdk deploy "*" --app="npx ts-node index.ts" --require-approval=never
      - cd ../client
      - S3_BUCKET=$SMM_SITE_S3_BUCKET sh ./update-files-headers-after-deploy.sh